/**
 * 
 */
package addBranch;

import gui.MainPage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import util.AlertUtil;
import util.DisplayUtil;
import util.GUIConstants;
import dao.DMLOperations;

/**
 * @author Dany
 *
 */
public class AddBranch extends JPanel{

    public JLabel branchId;
    public JLabel branchName;
    public JLabel branchAddress;
    public JLabel branchIdLabel;
    public JTextField branchNameText;
    public JTextField branchAddressText;
    public JButton addBranch;
    String cardNoDisplay="";
    
    public JLabel infoLabel;
    
    String bID="", bName="", bAddress="";


    public AddBranch() {

        /*super("LIBRARY MANAGEMENT SYSTEM");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setDefaultCloseOperation(EXIT_ON_CLOSE);   
        setSize(800, 620);
        setMinimumSize(new Dimension(800, 620));*/
    	
    	infoLabel=DisplayUtil.addInfoLabel("Tool Tip : Add branch section helps to add a new branch " +
    			"to the library system. Every branch will have an unique" +
    			" branch ID. This branch ID will be generated by the system." +
    			"If the branch name and address matches the existing branch then system wont allow to add a new branch");


    	branchName = new JLabel("Branch Name :");
    	branchName.setBounds(GUIConstants._XPOS_LEFT, GUIConstants._YPOS, 100, 20);
    	branchNameText = new JTextField(20);
    	branchNameText.setBounds(GUIConstants._XPOS_RIGHT, GUIConstants._YPOS, 200, 20);

    	branchAddress = new JLabel("Branch Address :");
    	branchAddress.setBounds(GUIConstants._XPOS_LEFT, GUIConstants._YPOS+30, 120, 20);
    	branchAddressText = new JTextField(20);
    	branchAddressText.setBounds(GUIConstants._XPOS_RIGHT, GUIConstants._YPOS+30, 200, 20);
    	
    	branchId = new JLabel("Branch ID:");
    	branchId.setBounds(GUIConstants._XPOS_LEFT, GUIConstants._YPOS+60, 100, 20);
    	branchIdLabel = new JLabel("");
    	branchIdLabel.setBounds(GUIConstants._XPOS_RIGHT, GUIConstants._YPOS+60, 400, 20);
    	
    	
    	
 
    	addBranch = new JButton("Add Branch");
    	addBranch.setBounds(GUIConstants._XPOS_LEFT+60, GUIConstants._YPOS+120, 100, 20);

    	addBranch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            	
            	bName=branchNameText.getText();
            	bAddress=branchAddressText.getText();
            	
            	if(bName.equals("")||bAddress.equals(""))
            	{
            	if(bName.equals(""))
            	{
            		AlertUtil.msgbox("Please enter the branch name");
            		branchNameText.requestFocusInWindow();
            	}else if(bAddress.equals(""))
            	{
            		AlertUtil.msgbox("Please enter the branch address");
            		branchAddressText.requestFocusInWindow();
            	}
            	
            	}else
            	{
            	
            	BranchBean branchBean = new BranchBean();
            	branchBean.setBranchName(bName);
            	branchBean.setBranchAddress(bAddress);
                try {
                    String res=new DMLOperations().insertBranch(branchBean);
                    if(res.contains("Exists"))
                    {
                    	cardNoDisplay = "The branch already "+res;
                    	branchIdLabel.setText(cardNoDisplay);
                    }else
                    {
                    	branchIdLabel.setText(res);

                    }
                } catch (Exception e1) {
                    e1.printStackTrace();
                }
            }
            }
        });
        setLayout(null);

        add(infoLabel);
        add(branchId);
        add(branchIdLabel);
        add(branchName);
        add(branchNameText);
        add(branchAddress);
        add(branchAddressText);

        add(addBranch);

        setVisible(true);
    }

    public static void main(String args[]) {
        new AddBranch();
    }
}
